version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install webpack
      - npm install webpack-cli@2.1.2
  pre_build:
    commands:
      - npm install -y
  build:
    commands:
      - npm run build
artifacts:
  files:
    - 'public/**/*'
    - appspec.yml
    - 'deploy-scripts/**/*' 